name: category
description: Group classification tool
version: 0.0.1
author: Thiltal <mlcoch.zdenek@gmail.com>

environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'
dependencies:
  angular: '4.0.0-alpha'
  angular_components: '0.6.0-alpha'
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  firebase:
    git: https://github.com/firebase/firebase-dart
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- angular:
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter