name: basic_http_server
version: 0.0.1
author: Seth Ladd <sethladd@gmail.com>
description: A minimal static HTTP server to demonstrate Dart on Heroku.
homepage: https://github.com/igrigorik/heroku-buildpack-dart
dependencies:
  browser: any
  postgresql: any
  shelf: any
  shelf_static: any
  sqljocky: any
